title: Lenovo ThinkBook 14-IML (Type 20RV) — OpenCore EFI for macOS
description: "Hackintosh OpenCore EFI guide for macOS Sequoia"
url: "https://karthik-kannekanti.github.io"
baseurl: "/Lenovo-ThinkBook14IML-EFI"
lang: en_US
author: Karthik-kannekanti
github_username: Karthik-kannekanti
repository: Karthik-kannekanti/Lenovo-ThinkBook14IML-EFI
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
keywords:
  - OpenCore
  - Hackintosh
  - macOS Sequoia
  - Lenovo ThinkBook 14-IML
  - EFI
  - UEFI bootloader
  - macOS on Lenovo
